apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: 192.168.0.210:8084/cicd_repo/spring-boot-app:41
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: spring-storage
          mountPath: /app  # Path inside the container where the volume will be mounted
      volumes:
      - name: spring-storage
        persistentVolumeClaim:
          claimName: my-pvc  # Name of the PVC
