apiVersion: apps/v1
kind: Deployment
metadata:
  name: maze-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maze-frontend
  template:
    metadata:
      labels:
        app: maze-frontend
    spec:
      containers:
        - name: maze-frontend-container
          image: 10.10.30.22:8085/thunderboltfront:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          
