apiVersion: apps/v1
kind: Deployment
metadata:
  name: maze-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maze-frontend
  template:
    metadata:
      labels:
        app: maze-frontend
    spec:
      containers:
        - name: maze-frontend-container
          image: 10.10.30.22:8085/thunderboltfront:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          volumeMounts:
            - mountPath: /test # Replace with the path in the container where you want to mount the volume
              name: maze-volume
      volumes:
        - name: maze-volume
          persistentVolumeClaim:
            claimName: maze-pv
