apiVersion: v1
kind: Service
metadata:
  name: maze-frontend-service
  namespace: test
spec:
  selector:
    app: maze-frontend
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30002
  type: NodePort
